language: cpp
before_install:
  - wget -O ~/vicr12345.gpg.key https://vicr123.com/repo/apt/vicr12345.gpg.key
  - sudo apt-key add ~/vicr12345.gpg.key
  - sudo add-apt-repository 'deb https://vicr123.com/repo/apt/ubuntu bionic main'
  - sudo apt-get update -qq
  - sudo apt-get install libphonon4qt5-dev libtag1-dev the-libs
script:
  - qmake
  - make
compiler:
  - gcc
dist: xenial
