sudo: required

services:
- docker

arch:
  #repos:
  #- theapps=http://packages.vicr123.com/arch/$arch
  packages:
  - git
  - qt5-base
  - qt5-charts
  - qt5-location
  - qt5-tools
  - phonon-qt5
  - the-libs
  script:
  - "./travis/build.sh"
  - "./travis/publish.sh"

after_success:
  
script:
- "wget -c https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh"
- "sed -i arch-travis.sh '49i--cap-add SYS_ADMIN --device /dev/fuse \\\\'"
- "cat arch-travis.sh | bash"

