sudo: required

services:
- docker

arch:
  #repos:
  #- theapps=http://packages.vicr123.com/arch/$arch
  packages:
  - git
  - qt5-base
  - qt5-charts
  - qt5-location
  - qt5-tools
  - phonon-qt5
  - the-libs
  script:
  - "./travis/build.sh"

after_success:
  
script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
- "./travis/publish.sh"

